// Function to create and append elements
function createElement(tag, attributes = {}, parent, innerText = '') {
    const element = document.createElement(tag);
    
    // Set attributes
    for (const key in attributes) {
        if (key === 'class') {
            element.className = attributes[key];
        } else if (key === 'style') {
            element.style.cssText = attributes[key];
        } else {
            element.setAttribute(key, attributes[key]);
        }
    }
    
    // Set inner text if provided
    if (innerText) {
        element.innerText = innerText;
    }
    
    // Append to parent if provided
    if (parent) {
        parent.appendChild(element);
    }
    
    return element;
}

// Function to build the webpage with all HTML5 tags
function buildWebpage() {
    // Document Structure
    const html = document.documentElement;
    const head = document.head;
    const body = document.body;

    // Metadata
    createElement('meta', { charset: 'UTF-8' }, head);
    createElement('meta', { name: 'viewport', content: 'width=device-width, initial-scale=1.0' }, head);
    createElement('title', {}, head, 'Comprehensive HTML5 Website');

    // Links and Scripts
    createElement('link', { rel: 'stylesheet', href: 'styles.css' }, head);
    createElement('script', { src: 'script.js', type: 'text/javascript' }, body);

    // Header
    const header = createElement('header', { style: 'background-color: #333; color: white; padding: 15px; text-align: center;' }, body);
    createElement('h1', {}, header, 'HTML5 Tag Demonstration');
    createElement('p', {}, header, 'This page contains all HTML5 elements generated by JavaScript.');

    // Navigation
    const nav = createElement('nav', { style: 'background-color: #444; color: white; padding: 10px; text-align: center;' }, body);
    createElement('a', { href: '#home', style: 'color: white; margin: 0 15px; text-decoration: none;' }, nav, 'Home');
    createElement('a', { href: '#about', style: 'color: white; margin: 0 15px; text-decoration: none;' }, nav, 'About');
    createElement('a', { href: '#services', style: 'color: white; margin: 0 15px; text-decoration: none;' }, nav, 'Services');
    createElement('a', { href: '#contact', style: 'color: white; margin: 0 15px; text-decoration: none;' }, nav, 'Contact');

    // Main Content
    const main = createElement('main', { style: 'display: flex; flex-direction: column; padding: 20px;' }, body);
    
    // Section
    const section = createElement('section', { style: 'padding: 20px; border: 1px solid #ccc; margin-bottom: 20px;' }, main);
    createElement('h2', {}, section, 'Main Section');
    createElement('p', {}, section, 'This is a main section demonstrating the use of various HTML5 tags.');

    // Article
    const article = createElement('article', { style: 'margin-top: 20px;' }, section);
    createElement('h3', {}, article, 'Article Title');
    createElement('p', {}, article, 'This is an article inside the main section.');
    
    // Figure and Figcaption
    const figure = createElement('figure', {}, article);
    createElement('img', { src: 'https://via.placeholder.com/150', alt: 'Placeholder Image' }, figure);
    createElement('figcaption', {}, figure, 'Figure 1: This is a caption for the image.');

    // Details and Summary
    const details = createElement('details', {}, article);
    createElement('summary', {}, details, 'Details Summary');
    createElement('p', {}, details, 'This is additional information that can be expanded.');

    // Form Elements
    const form = createElement('form', { action: '#', method: 'post', style: 'margin-top: 20px;' }, section);
    createElement('label', { for: 'name' }, form, 'Name: ');
    createElement('input', { type: 'text', id: 'name', name: 'name' }, form);
    createElement('br', {}, form);
    createElement('label', { for: 'email' }, form, 'Email: ');
    createElement('input', { type: 'email', id: 'email', name: 'email' }, form);
    createElement('br', {}, form);
    createElement('label', { for: 'password' }, form, 'Password: ');
    createElement('input', { type: 'password', id: 'password', name: 'password' }, form);
    createElement('br', {}, form);
    createElement('label', { for: 'file' }, form, 'Upload File: ');
    createElement('input', { type: 'file', id: 'file', name: 'file' }, form);
    createElement('br', {}, form);
    createElement('label', { for: 'color' }, form, 'Favorite Color: ');
    createElement('input', { type: 'color', id: 'color', name: 'color', value: '#ff0000' }, form);
    createElement('br', {}, form);
    createElement('label', { for: 'date' }, form, 'Date: ');
    createElement('input', { type: 'date', id: 'date', name: 'date' }, form);
    createElement('br', {}, form);
    createElement('label', { for: 'time' }, form, 'Time: ');
    createElement('input', { type: 'time', id: 'time', name: 'time' }, form);
    createElement('br', {}, form);
    createElement('button', { type: 'submit', style: 'margin-top: 10px;' }, form, 'Submit');
    
    // Embedded Elements
    createElement('iframe', { src: 'https://www.example.com', style: 'width: 100%; height: 300px; margin-top: 20px;' }, section);
    createElement('embed', { src: 'https://www.w3schools.com/html/horse.mp3', style: 'margin-top: 20px;' }, section);

    // List Elements
    const ul = createElement('ul', {}, section);
    createElement('li', {}, ul, 'List item 1');
    createElement('li', {}, ul, 'List item 2');
    createElement('li', {}, ul, 'List item 3');

    const ol = createElement('ol', {}, section);
    createElement('li', {}, ol, 'Ordered item 1');
    createElement('li', {}, ol, 'Ordered item 2');
    createElement('li', {}, ol, 'Ordered item 3');

    const dl = createElement('dl', {}, section);
    createElement('dt', {}, dl, 'Definition Term');
    createElement('dd', {}, dl, 'Definition Description');

    // Table
    const table = createElement('table', { style: 'width: 100%; margin-top: 20px; border: 1px solid #ccc;' }, section);
    const thead = createElement('thead', {}, table);
    const trHead = createElement('tr', {}, thead);
    createElement('th', {}, trHead, 'Header 1');
    createElement('th', {}, trHead, 'Header 2');
    createElement('th', {}, trHead, 'Header 3');
    
    const tbody = createElement('tbody', {}, table);
    for (let i = 0; i < 3; i++) {
        const tr = createElement('tr', {}, tbody);
        createElement('td', {}, tr, `Row ${i + 1}, Cell 1`);
        createElement('td', {}, tr, `Row ${i + 1}, Cell 2`);
        createElement('td', {}, tr, `Row ${i + 1}, Cell 3`);
    }

    // Embedded Media
    const video = createElement('video', { controls: '', style: 'display: block; margin-top: 20px; width: 100%; max-width: 600px;' }, section);
    createElement('source', { src: 'https://www.w3schools.com/html/mov_bbb.mp4', type: 'video/mp4' }, video);
    createElement('p', {}, section, 'Your browser does not support the video tag.');
    
    const audio = createElement('audio', { controls: '', style: 'display: block; margin-top: 20px;' }, section);
    createElement('source', { src: 'https://www.w3schools.com/html/horse.mp3', type: 'audio/mp3' }, audio);
    createElement('p', {}, section, 'Your browser does not support the audio tag.');

    // Asides
    const aside = createElement('aside', { style: 'background-color: #f4f4f4; padding: 20px; margin-top: 20px;' }, main);
    createElement('h2', {}, aside, 'Sidebar');
    createElement('p', {}, aside, 'This is an aside element.');

    // Footer
    const footer = createElement('footer', { style: 'background-color: #333; color: white; text-align: center; padding: 10px; margin-top: 20px;' }, body);
    createElement('p', {}, footer, '© 2024 Comprehensive HTML5 Website. All rights reserved.');
}

// Build the webpage when the document is loaded
document.addEventListener('DOMContentLoaded', buildWebpage);
